<?php

namespace common\models\content;

use common\models\elasticsearch\ArticleElasticModel;
use Yii;

/**
 * This is the model class for table "paragraph".
 *
 * @property int $paragraphId 段落ID
 * @property int $articleId 内容ID
 * @property int $orderId 段落顺序
 * @property string $cTime 添加时间
 * @property int $deleteFlag 删除标识:0正常，1删除
 */
class ParagraphModel extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'paragraph';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db_content');
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['articleId'], 'required'],
            [['articleId', 'orderId', 'deleteFlag'], 'integer'],
            [['cTime'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'paragraphId' => 'Paragraph ID',
            'articleId' => 'Article ID',
            'orderId' => 'Order ID',
            'cTime' => 'C Time',
            'deleteFlag' => 'Delete Flag',
        ];
    }

    public function afterFind()
    {
        $this->cTime = strtotime($this->cTime);
    }

    public function afterDelete()
    {
        ArticleElasticModel::create($this->articleId);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        ArticleElasticModel::create($this->articleId);
        parent::afterSave($insert, $changedAttributes);
    }
}